### PR TITLE
N2C14

### PR DESCRIPTION
**Pull request by nelegalno**
code style fixes
map:GetRealMapId() >> Nx.Map:GetRealMapId()
Updated TOC files to Live version and add "D" at the end of the Title and Version to indicate it's the Dev version

### CODE REVIEW

**Comment by samyonair** [comment]
Have assigned Rythal to it, because he should make a decisson about it, sorry for merge failure by itallian language merge

**Comment by nelegalno** [comment]
np, I believe the translations should take priority.
And it's a good idea to get Rythal's opinion on the .toc and Carbonite/NxTravel.lua file changes.

**Comment by nelegalno** [comment]
Updated:
whitespace
Simplified translation files
Removed unused strings from Carbonite/Bindings.xml
Added missing line in [Carbonite.Quests/Locales/deDE.lua#L20] (https://github.com/nelegalno/Carbonite/blob/N2C14/Carbonite.Quests/Locales/deDE.lua#L20)

P.S. #271 shouldn't cause merge conflict.

**Comment by samyonair** [comment]
hi nelegalno just for testing purpose and development have created branch DEV, can you please make a pull request there? 

Because from my understandig Rythal is out by now

Greetings Samyonair

**Pull request closed without merging**
