### PR TITLE
Fixed ids npc ids for DoK

### PR DESCRIPTION
**Pull request by JWMcQuire**
After my first pull request, I corrected the ids for Exarch Akama and Yrel, so that should complete the edits I have done so far in the 91-100 lua file.

I hope I did it right this time, and that my edits are approved.

### CODE REVIEW

**Comment by JWMcQuire** [comment]
I believe I really messed up this pull request and since I have made several more edits to this and another file. So I was wondering if this pull request can be removed so do a proper pull without the conflicts and edits I didn't make. I'm still trying to get a handle on syncing with the Dev branch without messing up my local files which I now make backups of to preserve my edits for when I mess it up.

I appreciate any advice that can be offered. I believe I have looked at everything in the tutorial and the help area, but can't find (or am missing) information on how to request a pull from my master to the Dev. branch.

**Comment by atk** [comment]
You could close the pull request yourself. If I were you, I'd stash your changes, check out the current version and cherry-pick from the stash.

**Comment by IrcDirk** [comment]
For someone who just is learnig git that will be hard ^^

**Comment by JWMcQuire** [comment]
To you both, thanks for your comments and closing the pull. Yes, I'm new at this, but making the edits are the easy part, just Github is the hard part. The tutorial was helpful an many ways getting me set up with this, but not so much how to submit pull requests based on author preferences. So any advice would definitely be helpful.

@IrcDirk: So I should download the Dev version and overwrite the files I "cloned" from the master and compare my edits with that?

Anyway, I just want to help any way I can, but I don't want to step on any toes or cause any unnecessary stress. Beyond that, I appreciate all the hard work that Rythal and you guys have put into this to make navigating WoW so much easier than without it.

**Pull request closed without merging**
