### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Adam111**

### CODE REVIEW

**Comment by IrcDirk** [comment]
These should go to DEV branch u are making fixes for Pre-Patch and Legion?

**Comment by Adam111** [comment]
These fixes aren't 7.0.3 specific.

**Comment by IrcDirk** [comment]
Even if not these should go to DEV branch and should be tested before making into Master. So please make pull request to DEV branch and close this.

**Comment by Rythal** [comment]
It's ok, since all the changes i've made to dev to fix pre-patch are in the Master i'm going to kill the dev branch tonight.

**Comment by IrcDirk** [comment]
Rythal Master and DEV are not equal: 

**This (DEV) branch is 21 commits ahead, 9 commits behind master.** 

So make sure u check those ahead commits before u kill DEV ;)

**Comment by Rythal** [comment]
I never will understand the emails git sends me... I thought the fixes I was making in dev were being pulled by someone else into Master.... but it's all moot now, I resolved the conflicts and brought the 21 commits across, so now dev is the one behind.

**Comment by IrcDirk** [comment]
Great. So now you can kill DEV branch ;)

**Pull request merged**
