### PR TITLE
Added some Objectives and fixed NPC locations

### PR DESCRIPTION
**Pull request by JWMcQuire**
While building my Garrison after arriving at Draenor, I found some minor
issues with some quests "not in database" and npc and objective coordinates
wrong after Garrison is built. So I made some edits that "add" those
quests to the database and changed npc/objective coordinates to
accurately reflect their locations.

I only intended to submit the edits in the 86-90 lua because I haven't finished the edits in the 91-100  lua regarding "The Defense of Karabor" quest where I attempted to add objectives and coordinates for Arnokk the Burner's location at 76.90, 40.60 and Yrel's location which is also where the final stage occurs anyway. I think the last thing I need to do is correct the locations and npc ids for  Exarch Akama and Yrel. I also haven't tested it yet, so I don't know if the objectives and locations for this quest will show up right. So you can probably ignore this until I finish and test it.

I have tested the changes in the 86-90 lua, so that is really what I wanted to submit anyway.

This is my first time submitting edits on this site, so I hope I did it right.

### CODE REVIEW

**Comment by Rythal** [comment]
You were close to right, you need to change branches from Master to Dev before pushing / submitting.

**Comment by JWMcQuire** [comment]
Thanks, I’ll do that right away.

**Comment by JWMcQuire** [comment]
Sorry to bother you again. I noticed some merge requests and was wondering if you need me to resubmit this pull or make sure future pulls are sent to the Dev branch.

**Comment by Rythal** [comment]
I may need to manually merge it. It appears to be trying to include more then just the changes you made.

**Comment by JWMcQuire** [comment]
Ok, let me know if I need to resubmit. I already corrected the npc ids for "The Defense of Karabor" and committed them to my fork. I'll wait to see what else I need to do before gong further with this.

**Pull request closed without merging**
