### PR TITLE
fix for questwatch quest item button - i hope ;)

### PR DESCRIPTION
**Pull request by deathcore01**
please test it, i have no longer this bug a i'm not sure that i have
found all for this bug.

this commit include many other fixes and optimizations for questwatch
frame...

### CODE REVIEW

**Comment by atk** [comment]
> this commit include many other fixes and optimizations for questwatch frame...

I dislike mixed commits - this way, one cannot easily figure out what the fix is and what it is not.

**Comment by deathcore01** [comment]
i have commented all in the code and the changes are very small...

**Comment by atk** [comment]
I don't see how reducing the initial timeout will help fixing that. It is there for a very good reason. Yes, we do like performance for our addon, but we don't like our addon hogging performance from the game or other addons, therefore the timeout.

**Comment by deathcore01** [comment]
initial timeout will not fixing the bug, is a optimization only and can removed, was only a idea for speedup

**Comment by atk** [comment]
Your configuration is probably powerful enough - and as I see you have already reduced the numbers of quests loaded at init, which is not a default setting.

**Comment by deathcore01** [comment]
ih this fix? i have not reduced the numbers of quests loaded in this fix...is the var qLoadLevel? this come from a earlier fix, the var qLoadLevel was present into the code a any option for it was missing, i have added it and i think, this is a good idea to reduce memory usage automatical. by default this option is deactivated.

**Comment by atk** [comment]
Since you don't want to reduce your commit to only the lines that are actually required to fix the problem, I will cherry-pick the fix later.

**Comment by deathcore01** [comment]
i can't, i have a problem with the repo and i have my fork deleted - so close this commit and i can send it new with a new fork

**Comment by atk** [comment]
Closed by request

**Pull request closed without merging**
