### PR TITLE
I made several edits correcting some NPC Ids, removing some quest objectives, etc.

### PR DESCRIPTION
**Pull request by JWMcQuire**
You can ignore the commit from Rythal's dev which was just me updating that file to my repository.

The rest are as follows:
I experimented with Unwelcome Memories (Delvar Ironfist's Wingman quest) adding just his NPC Id to get the quest to show in database. This edit fixed that issue.

Ancient Protectors in Quests41-50.lua wasn't showing in database, so I added a line giving the Starting quest information.

Several minor edits to get quests into database is just more of what I have done to get quests into the database. Removing the objective information for "Born to Shred" fixed the issue of it not showing in the database. If this can be done for other quests with objective info, then maybe we can shrink this file which may speed up processing of quests in-game.

Vol'mar was showing on the map as an Alliance flight path instead of Horde. So I edited the file to correct that issue.

You may ignore "Updating my Dev to Latest version" I just copied my Carbonite files from my game Addons folder to my Github folder. It is just the latest edition with my edits as listed.

### CODE REVIEW

**Comment by JWMcQuire** [comment]
The conflict exists with my including my update from  Rythal's dev. I don't know how to exclude it. So hopefully it can be resolved.

**Comment by JWMcQuire** [comment]
I closed this pull request because of the conflict and will submit the non-conflicting commits individually. My apologies for this error.

**Comment by IrcDirk** [comment]
no problem, we all are learing ;)

**Comment by JWMcQuire** [comment]
Thanks. :)

**Pull request closed without merging**
