### PR TITLE
	 - Added Missing L[..] to Carbonite.Quests - Added Missing Strings in Carbonite.Weekly

### PR DESCRIPTION
**Pull request by gOOvER**
- Updated Carbonite.Quest with missing L[...] -> All languagefiles
- Updated Carbonite.Weekly with missing L[...] -> All Languagefiles

### CODE REVIEW

**Comment by gOOvER** [comment]
Why do you close it?  LibBabble only few changes i i don't want to loose 2h of work on Strings. 

Please reopen that atk. i remove the few lines.

**Comment by gOOvER** [comment]
Sooo, LibBabble-Boss is removed and i updated all Translations in Carbonite.Weekly that all match the actual Translations :)

**Comment by atk** [comment]
You are aware that Nx.prt is mostly used for debug output? Translating that would only lead to confusion, since the developers would have to look up all those messages in the translation tables, which would be a waste of their valuable time.

**Comment by gOOvER** [comment]
I know that.  But some will be printed in Chat to give info's also for Users.

I do not added to all nx.prt Strings


Am 1. Januar 2015 10:13:06 schrieb Alex Lohr <notifications@github.com>:

**Comment by atk** [comment]
OK. I'll merge this later when I have the time to test for errors and will discuss the decision not to translate certain messages when we translate the stuff.

**Pull request merged**
